apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyunseok-practice
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
-namespace.yaml
images:
- name: hynseok/gitops
  newTag: "74"
