apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hynseok-practice
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml

images:
- name: hynseok/simple-webserver
  newTag: 7b80bf0940899f02f66b0b3ad9cd7a87e07ecfd4
